name: app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  shared_preferences: ^0.5.6+3
  jaguar_jwt: ^2.1.6
  flutter_i18n: 0.8.0
  image_picker: ^0.6.5
  http: ^0.12.0+4
  http_parser: ^3.1.4
  flutter_xlider: ^3.2.0
  intl: ^0.16.0
  flutter_holo_date_picker: ^0.1.3+3
  smooth_star_rating: 1.1.1
  firebase_messaging: ^6.0.16
  firebase_crashlytics: ^0.1.3+3
  cached_network_image: ^2.2.0+1
  provider: ^4.0.4
  recase: ^3.0.0
  openapi:
    path: ./openapi

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/i18n/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand_Thin.otf
          weight: 200
        - asset: assets/fonts/Quicksand_Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand_Light_Oblique.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Quicksand_Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand_Regular_Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Quicksand_Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand_SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand_Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand_Bold_Oblique.otf
          weight: 700
          style: italic
    - family: PIcons
      fonts:
        - asset: assets/fonts/patates_icons.ttf
#icon_font_generator --from=assets/icons --class-name=PIcons --out-font=assets/fonts/patates_icons.ttf --out-flutter=lib/design_system/icons.dart